"""auto-20251109113435

Revision ID: 2f3258f667c1
Revises: c83013567e66
Create Date: 2025-11-09 11:34:42.108976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3258f667c1'
down_revision: Union[str, None] = 'c83013567e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs'))
    )
    op.create_index(op.f('ix_tariffs_name'), 'tariffs', ['name'], unique=True)
    op.create_table('tariff_files',
    sa.Column('tariff_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_tariff_files_tariff_id_tariffs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff_files')),
    sa.UniqueConstraint('file_path', name=op.f('uq_tariff_files_file_path'))
    )
    op.create_index(op.f('ix_tariff_files_tariff_id'), 'tariff_files', ['tariff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_files_tariff_id'), table_name='tariff_files')
    op.drop_table('tariff_files')
    op.drop_index(op.f('ix_tariffs_name'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
