"""auto-20251122091159

Revision ID: b618ec5853ee
Revises: 3516fa16368a
Create Date: 2025-11-22 09:12:17.098411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b618ec5853ee'
down_revision: Union[str, None] = '3516fa16368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_links',
    sa.Column('download_uuid', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['tariff_files.id'], name=op.f('fk_download_links_file_id_tariff_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_links'))
    )
    op.create_index(op.f('ix_download_links_download_uuid'), 'download_links', ['download_uuid'], unique=True)
    op.create_index(op.f('ix_download_links_file_id'), 'download_links', ['file_id'], unique=False)
    op.create_index(op.f('ix_download_links_user_email'), 'download_links', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_links_user_email'), table_name='download_links')
    op.drop_index(op.f('ix_download_links_file_id'), table_name='download_links')
    op.drop_index(op.f('ix_download_links_download_uuid'), table_name='download_links')
    op.drop_table('download_links')
    # ### end Alembic commands ###
